Repository dmlal/BackOffice, pull requests merged in 2023-12, with the labels that each got.

#2 프로젝트 공통 구현
  build.gradle
  src/main/java/com/sparta/backoffice/auth/dto/TokenDto.java
  src/main/java/com/sparta/backoffice/global/annotation/AuthUser.java
  src/main/java/com/sparta/backoffice/global/aop/GlobalExceptionHandler.java
  src/main/java/com/sparta/backoffice/global/config/SecurityConfig.java
  src/main/java/com/sparta/backoffice/global/config/SwaggerConfig.java
  src/main/java/com/sparta/backoffice/global/constant/ErrorCode.java
  src/main/java/com/sparta/backoffice/global/exception/ApiException.java
  src/main/java/com/sparta/backoffice/global/properties/JwtProperties.java
  src/main/java/com/sparta/backoffice/global/security/CustomUserDetailService.java
  src/main/java/com/sparta/backoffice/global/security/CustomUserDetails.java
  src/main/java/com/sparta/backoffice/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/backoffice/global/util/JwtProvider.java
  src/main/java/com/sparta/backoffice/global/util/RedisUtils.java
  src/main/resources/application.properties
Labels: enhancement

#3 인증 API - 로그인, 회원가입 구현
  src/main/java/com/sparta/backoffice/BackOfficeApplication.java
  src/main/java/com/sparta/backoffice/auth/controller/AuthController.java
  src/main/java/com/sparta/backoffice/auth/dto/request/LoginRequest.java
  src/main/java/com/sparta/backoffice/auth/dto/request/SignupRequest.java
  src/main/java/com/sparta/backoffice/auth/service/AuthService.java
  src/main/java/com/sparta/backoffice/global/aop/GlobalExceptionHandler.java
  src/main/java/com/sparta/backoffice/global/config/SecurityConfig.java
  src/main/java/com/sparta/backoffice/global/constant/ErrorCode.java
  src/main/java/com/sparta/backoffice/global/constant/ResponseCode.java
  src/main/java/com/sparta/backoffice/user/constant/UserRoleEnum.java
  src/main/java/com/sparta/backoffice/user/entity/User.java
  src/main/resources/application.properties
Labels: enhancement

#5 토큰 검증 redis utils 제거 수정
  src/main/java/com/sparta/backoffice/global/config/SecurityConfig.java
  src/main/java/com/sparta/backoffice/global/security/JwtAuthorizationFilter.java
Labels: bug, enhancement

#8 settings.gradle 수정
  settings.gradle
Labels: enhancement

#15 merge Feat/admin
  src/main/java/com/sparta/backoffice/global/aop/GlobalExceptionHandler.java
  src/main/java/com/sparta/backoffice/global/config/SecurityConfig.java
  src/main/java/com/sparta/backoffice/global/constant/ErrorCode.java
  src/main/java/com/sparta/backoffice/global/constant/ResponseCode.java
  src/main/java/com/sparta/backoffice/global/exception/ApiException.java
  src/main/java/com/sparta/backoffice/global/security/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/backoffice/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/backoffice/post/controller/PostAdminController.java
  src/main/java/com/sparta/backoffice/post/controller/PostController.java
  src/main/java/com/sparta/backoffice/user/controller/AdminUserConroller.java
  src/main/java/com/sparta/backoffice/user/controller/UserController.java
  src/main/java/com/sparta/backoffice/user/dto/UserInfoDto.java
  src/main/java/com/sparta/backoffice/user/dto/request/ProfileUpdateRequestDto.java
  src/main/java/com/sparta/backoffice/user/service/UserService.java
Labels: enhancement

#17 인증 API - 토큰 재발급, 로그아웃 구현
  src/main/java/com/sparta/backoffice/auth/controller/AuthController.java
  src/main/java/com/sparta/backoffice/auth/entity/Logout.java
  src/main/java/com/sparta/backoffice/auth/entity/RefreshToken.java
  src/main/java/com/sparta/backoffice/auth/repository/LogoutRepository.java
  src/main/java/com/sparta/backoffice/auth/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/backoffice/auth/service/AuthScheduleService.java
  src/main/java/com/sparta/backoffice/auth/service/AuthService.java
  src/main/java/com/sparta/backoffice/global/config/SchedulerConfig.java
  src/main/java/com/sparta/backoffice/global/constant/ErrorCode.java
  src/main/java/com/sparta/backoffice/global/constant/ResponseCode.java
  src/main/java/com/sparta/backoffice/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/backoffice/global/util/RedisUtils.java
Labels: enhancement

#19 refactor : 상태코드 변경
  src/main/java/com/sparta/backoffice/follow/controller/FollowController.java
  src/main/java/com/sparta/backoffice/follow/service/FollowService.java
  src/main/java/com/sparta/backoffice/global/constant/ResponseCode.java
  src/main/java/com/sparta/backoffice/user/controller/UserController.java
Labels: enhancement

#21 Fix: 코드 유실 수정
  src/main/java/com/sparta/backoffice/auth/entity/Logout.java
  src/main/java/com/sparta/backoffice/global/config/SecurityConfig.java
Labels: bug

#26 인증 API - 소셜 로그인 (네이버, 카카오) 구현
  build.gradle
  src/main/java/com/sparta/backoffice/global/config/SecurityConfig.java
  src/main/java/com/sparta/backoffice/global/constant/SocialType.java
  src/main/java/com/sparta/backoffice/global/security/CustomUserDetails.java
  src/main/java/com/sparta/backoffice/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/sparta/backoffice/global/security/oauth/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/sparta/backoffice/global/security/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/sparta/backoffice/global/security/oauth/user/KakaoOAuth2UserDetails.java
  src/main/java/com/sparta/backoffice/global/security/oauth/user/NaverOAuth2UserDetails.java
  src/main/java/com/sparta/backoffice/global/security/oauth/user/OAuth2Attributes.java
  src/main/java/com/sparta/backoffice/global/security/oauth/user/OAuth2UserDetails.java
  src/main/java/com/sparta/backoffice/global/security/oauth/user/OAuth2UserInfoFactory.java
  src/main/java/com/sparta/backoffice/user/dto/UserInfoDto.java
  src/main/java/com/sparta/backoffice/user/entity/User.java
  src/main/java/com/sparta/backoffice/user/repository/UserRepository.java
  src/main/resources/application.properties
Labels: enhancement

#33 인증 API 테스트 구현
  src/main/resources/application-local.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/com/sparta/backoffice/auth/controller/AuthControllerTest.java
  src/test/java/com/sparta/backoffice/helper/JwtAuthenticationHelper.java
Labels: enhancement

#34 리팩토링: Factory class private 생성자 추가
  src/main/java/com/sparta/backoffice/global/security/oauth/user/OAuth2UserInfoFactory.java
Labels: enhancement

#36 README.md 파일 추가
  README.md
Labels: documentation

#38 Add: README API 명세 스크린샷 추가
  README.md
Labels: documentation

#39 Update README.md
  README.md
Labels: enhancement
